// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnir2rGVEJqR13Y02rIQRupzPFy8WJklY',
    appId: '1:494411912282:android:43e256f9c3535357e93463',
    messagingSenderId: '494411912282',
    projectId: 'freematch-d70af',
    databaseURL:
        'https://freematch-d70af-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'freematch-d70af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHfE_pr2eGey4R2Xboux8FisqZbXBU7jo',
    appId: '1:494411912282:ios:1e01b1ed4b525c65e93463',
    messagingSenderId: '494411912282',
    projectId: 'freematch-d70af',
    databaseURL:
        'https://freematch-d70af-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'freematch-d70af.firebasestorage.app',
    iosBundleId: 'com.freematch.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByBlu0frrDMWTdljzQ-S9XjMX_pApkBlQ',
    appId: '1:494411912282:web:830bcebadbd61577e93463',
    messagingSenderId: '494411912282',
    projectId: 'freematch-d70af',
    authDomain: 'freematch-d70af.firebaseapp.com',
    databaseURL:
        'https://freematch-d70af-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'freematch-d70af.firebasestorage.app',
    measurementId: 'G-NH4P6GCNJB',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHfE_pr2eGey4R2Xboux8FisqZbXBU7jo',
    appId: '1:494411912282:ios:1e01b1ed4b525c65e93463',
    messagingSenderId: '494411912282',
    projectId: 'freematch-d70af',
    databaseURL:
        'https://freematch-d70af-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'freematch-d70af.firebasestorage.app',
    iosBundleId: 'com.freematch.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByBlu0frrDMWTdljzQ-S9XjMX_pApkBlQ',
    appId: '1:494411912282:web:375c1567aedc6e30e93463',
    messagingSenderId: '494411912282',
    projectId: 'freematch-d70af',
    authDomain: 'freematch-d70af.firebaseapp.com',
    databaseURL:
        'https://freematch-d70af-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'freematch-d70af.firebasestorage.app',
    measurementId: 'G-PB0B85RB2S',
  );
}
