import 'package:flutter/material.dart';

class EulaScreen extends StatelessWidget {
  const EulaScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFF0F172A),
      appBar: AppBar(
        title: const Text("End User License Agreement (EULA)"),
        backgroundColor: const Color(0xFF1E293B),
        foregroundColor: Colors.white,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text(
              "End User License Agreement",
              style: TextStyle(
                color: Colors.white,
                fontSize: 24,
                fontWeight: FontWeight.bold,
              ),
            ),
            const SizedBox(height: 16),
            Text(
              "Welcome to FreeMatch. By using this application, you agree to the following terms and conditions. If you do not agree to these terms, please do not use the application.",
              style: TextStyle(
                color: Colors.grey[400],
                fontSize: 16,
                height: 1.5,
              ),
            ),
            const SizedBox(height: 24),
            _buildSection(
              "1. User-Generated Content (UGC)",
              "FreeMatch allows users to create and share content through profiles and chat. We are committed to maintaining a safe environment. By using FreeMatch, you agree that you will not post content that is:\n"
                  "• Obscene, pornographic, or sexually explicit.\n"
                  "• Hateful, threatening, or discriminatory.\n"
                  "• Harassing or promoting abuse.\n"
                  "• Illegal or promoting illegal activities.",
            ),
            _buildSection(
              "2. Content Moderation",
              "FreeMatch has a zero-tolerance policy for objectionable content or abusive users. We reserve the right, but are not obligated, to:\n"
                  "• Review and remove content that violates this agreement.\n"
                  "• Block or terminate the accounts of users who violate these terms without prior notice.",
            ),
            _buildSection(
              "3. User Reporting and Blocking",
              "Users can report any content or person that violates these terms. We provide tools to:\n"
                  "• Report objectionable content.\n"
                  "• Block abusive users.\n"
                  "Reports are reviewed within 24 hours. Actions taken against violating users may include content removal and permanent account suspension.",
            ),
            _buildSection(
              "4. Liability",
              "FreeMatch is not responsible for the content generated by users but will take appropriate action as outlined above to maintain community standards.",
            ),
            const SizedBox(height: 40),
            Center(
              child: Text(
                "Last Updated: February 7, 2026",
                style: TextStyle(color: Colors.grey[500], fontSize: 12),
              ),
            ),
            const SizedBox(height: 20),
          ],
        ),
      ),
    );
  }

  Widget _buildSection(String title, String content) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 24.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: const TextStyle(
              color: Colors.white,
              fontSize: 18,
              fontWeight: FontWeight.bold,
            ),
          ),
          const SizedBox(height: 8),
          Text(
            content,
            style: TextStyle(
              color: Colors.grey[400],
              fontSize: 14,
              height: 1.5,
            ),
          ),
        ],
      ),
    );
  }
}
